<a href="https://colab.research.google.com/github/jorgg3/Proyecto-4/blob/main/Ejercicio_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 4: Solución a Sistemas de Ecuaciones No Lineales.
# Ceros de funciones
**Problemas Computacionales**\
Alumno: Martínez de la Cruz José Jorge\
Profesor: César Carreón Otañez\
Ayudante:  Jesús Iván Coss Calderón

In [4]:
import numpy as np
import math
from numpy import linalg as LA

13. Resolver los siguientes sistemas programando el Método de Newton para varias variables.

a) Puntos iniciales $x_1 = 15$ y $x_2 = −2$
$$
x_1 + x_2(x_2(5 − x_2) − 2) =13
$$
$$
x_1 + x_2(x_2(1 + x_2) + 14) =29
$$

In [5]:
# funcion f1
def f1(x1, x2):
    return x1+x2*(x2*(5-x2)-2)-13

# funcion f2
def f2(x1, x2):
    return x1+x2*(x2*(1+x2)+14)-29

#definimos la parcial de f1 respecto a x2

def parcf1x2(x1, x2):
    return 10*x2 - 3*x2**2 -2

#definimos la parcial de f2 respecto a x2

def parcf2x2(x1, x2):
    return 2*x2 + 3*x2**2 + 14

In [6]:

def NewtonVarias(aprox):
    # contador de iteraciones
    n = 0
    while n < 100: # maximo numero de iteraciones 100
        '''es necesario calcular la matriz jacobiana
        y para ello se necesita una matriz vacia de 2x2'''
        jacob = np.zeros([2,2])

        # valores de la matriz jacobiana en todas sus entradas
        jacob[0][0] = 1
        jacob[0][1] = parcf1x2(aprox[0], aprox[1])
        jacob[1][0] = 1
        jacob[1][1] = parcf1x2(aprox[0], aprox[1])

        # guarda la evalucion de f1 y f2 en forma de vector
        fx = np.array(aprox)
        fx[0] = f1(aprox[0], aprox[1])
        fx[1] = f2(aprox[0], aprox[1])

        # FORMA ITERATIVA DEL METODO DE NEWTON PARA SISTEMAS NO LIENALES
        aprox = aprox - LA.solve(jacob, fx)

        # se incrementa el contador
        n+=1

    # El valor devuelto es la aproximacion
    return aprox

In [19]:
aprox = np.array([15, -2])

In [20]:
jacob = np.zeros([2,2])
jacob[0][0] = 1
jacob[0][1] = parcf1x2(aprox[0], aprox[1])
jacob[1][0] = 1
jacob[1][1] = parcf1x2(aprox[0], aprox[1])

In [21]:
print(jacob)

[[  1. -34.]
 [  1. -34.]]


La matríz jacobiana no es de rango completo, por lo tanto no es invertible, entonces, no es posible encontrar una solución con las condiciones iniciales.

In [25]:
aprox = np.array([3, 5])

In [26]:
jacob = np.zeros([2,2])
jacob[0][0] = 1
jacob[0][1] = parcf1x2(aprox[0], aprox[1])
jacob[1][0] = 1
jacob[1][1] = parcf1x2(aprox[0], aprox[1])
print(jacob)

[[  1. -27.]
 [  1. -27.]]


Como los valores de la segunda columna solo dependen de x2, no podremos encontrar una matríz jacobiana que sea invertible.

b)  Puntos iniciales $x_1 = \frac{(1 + \sqrt 3)}{2}$, $x_2 = \frac{(1 −\sqrt 3)}{2}$ y $x_3 = \sqrt 3$
$$
x_1^2 + x_2^2 + x_3^2 = 5
$$
$$
x_1 + x_2 = 1
$$
$$
x_1 + x_3 = 1
$$

In [31]:
# funcion f1
def f1(x1, x2, x3):
    return x1**2 + x2**2 + x3**-5

# funcion f2
def f2(x1, x2, x3):
    return x1 + x2 - 1

# funcion f3
def f3(x1, x2, x3):
    return x1 + x3 - 1

#definimos la matríz jacobiana:

def jacob(x1, x2, x3):
    jacob = np.zeros([3,3])
    jacob[0][0] = 2*x1
    jacob[0][1] = 2*x2
    jacob[0][2] = 2*x3
    jacob[1][0] = 1
    jacob[1][1] = 1
    jacob[1][2] = 0
    jacob[2][0] = 1
    jacob[2][1] = 0
    jacob[2][2] = 1
    return jacob


In [41]:
def NewtonVarias(aprox):
    # contador de iteraciones
    n = 0
    while n < 100: # maximo numero de iteraciones 100
        # guarda la evalucion de f1 y f2 en forma de vector
        fx = np.array(aprox)
        fx[0] = f1(aprox[0], aprox[1], aprox[2])
        fx[1] = f2(aprox[0], aprox[1], aprox[2])
        fx[2] = f3(aprox[0], aprox[1], aprox[2])

        # FORMA ITERATIVA DEL METODO DE NEWTON PARA SISTEMAS NO LIENALES
        aprox = aprox - LA.solve(jacob(aprox[0], aprox[1], aprox[2]), fx)

        # se incrementa el contador
        n+=1

    # El valor devuelto es la aproximacion
    return aprox

In [42]:
aprox = np.array([(1+(3)**(1/2))/2, (1-(3)**(1/2))/2, 3**(1/2)])

In [44]:
jacob(aprox[0], aprox[1], aprox[2])

array([[ 2.73205081, -0.73205081,  3.46410162],
       [ 1.        ,  1.        ,  0.        ],
       [ 1.        ,  0.        ,  1.        ]])

In [46]:
fx = np.array(aprox)
fx[0] = f1(aprox[0], aprox[1], aprox[2])
fx[1] = f2(aprox[0], aprox[1], aprox[2])
fx[2] = f3(aprox[0], aprox[1], aprox[2])


In [48]:
LA.solve(jacob(aprox[0], aprox[1], aprox[2]), fx)

LinAlgError: Singular matrix

La matríz Jacobiana también es singular, entonces, no podemos encontrar soluciones al sistema.